-- One monthly payout row per staff member (unique on staff_id + month).
-- Generated by admin/payout/generate.php from attendance + leave data,
-- reviewed/adjusted as 'draft', then locked via 'finalized' and later
-- 'paid'. See CLAUDE.md "Payout" for the exact calculation.
CREATE TABLE IF NOT EXISTS payouts (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  staff_id INT UNSIGNED NOT NULL,
  month CHAR(7) NOT NULL COMMENT 'YYYY-MM',
  base_salary DECIMAL(12,2) NOT NULL,
  present_days INT UNSIGNED NOT NULL DEFAULT 0,
  absent_days INT UNSIGNED NOT NULL DEFAULT 0,
  on_leave_days INT UNSIGNED NOT NULL DEFAULT 0,
  wfh_days INT UNSIGNED NOT NULL DEFAULT 0,
  half_days INT UNSIGNED NOT NULL DEFAULT 0,
  unpaid_deduction DECIMAL(12,2) NOT NULL DEFAULT 0,
  bonus DECIMAL(12,2) NOT NULL DEFAULT 0,
  net_payout DECIMAL(12,2) NOT NULL DEFAULT 0,
  status ENUM('draft','finalized','paid') NOT NULL DEFAULT 'draft',
  generated_by INT UNSIGNED NULL,
  generated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  paid_at TIMESTAMP NULL,
  UNIQUE KEY uniq_payouts_staff_month (staff_id, month),
  KEY idx_payouts_month (month),
  KEY idx_payouts_status (status),
  FOREIGN KEY (staff_id) REFERENCES staff(id) ON DELETE CASCADE,
  FOREIGN KEY (generated_by) REFERENCES admins(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
